server: 
  host: 'localhost'
  port: '8080'
socket:
  host: 'localhost'
  port: '8080'
auth:
  enabled: true
  realm: http://bamboozle.herokuapp.com
  return: http://bamboozle.herokuapp.com/auth/google/return
mock: ./config/mock.yml
