server: 
  host: 'localhost'
  port: '8080'
socket:
  host: 'localhost'
  port: '8080'
auth:
  enabled: true
  realm: http://localhost:8080
  return: http://localhost:8080/auth/google/return
mock: ./config/mock.yml
